// Package jwt handles RS256 JWT signing and verification backed by a
// rotating keychain stored in PostgreSQL.
package jwt

import (
	"context"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"time"

	"github.com/danielmnuoz/vendex/services/auth/internal/crypto"
	"github.com/danielmnuoz/vendex/services/auth/internal/store"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

type Signer struct {
	store store.Store
	aead  *crypto.AEAD
}

func NewSigner(s store.Store, a *crypto.AEAD) *Signer {
	return &Signer{store: s, aead: a}
}

type Claims struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
	jwt.RegisteredClaims
}

// Sign signs a token using the currently active signing key. The token's
// `kid` header lets verifiers pick the right public key from the JWKS.
func (s *Signer) Sign(ctx context.Context, userID uuid.UUID, role string, ttl time.Duration) (string, time.Time, error) {
	key, err := s.store.GetActiveSigningKey(ctx)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("get active key: %w", err)
	}
	priv, err := s.decodePrivate(key)
	if err != nil {
		return "", time.Time{}, err
	}
	now := time.Now().UTC()
	exp := now.Add(ttl)
	claims := Claims{
		UserID: userID,
		Role:   role,
		RegisteredClaims: jwt.RegisteredClaims{
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(exp),
			Subject:   userID.String(),
		},
	}
	tok := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	tok.Header["kid"] = key.ID.String()
	signed, err := tok.SignedString(priv)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("sign: %w", err)
	}
	return signed, exp, nil
}

// Verify parses and validates a token, looking up the public key by `kid`.
// Returns the claims if the token is signed by a known non-revoked key
// and not expired.
func (s *Signer) Verify(ctx context.Context, raw string) (Claims, error) {
	var claims Claims
	_, err := jwt.ParseWithClaims(raw, &claims, func(t *jwt.Token) (any, error) {
		if t.Method != jwt.SigningMethodRS256 {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		kidStr, _ := t.Header["kid"].(string)
		if kidStr == "" {
			return nil, errors.New("missing kid header")
		}
		kid, err := uuid.Parse(kidStr)
		if err != nil {
			return nil, fmt.Errorf("invalid kid: %w", err)
		}
		k, err := s.store.GetSigningKeyByID(ctx, kid)
		if err != nil {
			return nil, fmt.Errorf("lookup kid %s: %w", kid, err)
		}
		if k.RevokedAt != nil {
			return nil, errors.New("signing key revoked")
		}
		return decodePublic(k.PublicKeyPEM)
	})
	if err != nil {
		return Claims{}, err
	}
	return claims, nil
}

func (s *Signer) decodePrivate(k store.SigningKey) (*rsa.PrivateKey, error) {
	pemBytes, err := s.aead.Decrypt(k.PrivateKeyEncrypted)
	if err != nil {
		return nil, fmt.Errorf("decrypt private key: %w", err)
	}
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, errors.New("decode PEM: no block found")
	}
	priv, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		// Try PKCS8 as a fallback for keys generated by other tools.
		any, err2 := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err2 != nil {
			return nil, fmt.Errorf("parse private key: pkcs1=%v pkcs8=%v", err, err2)
		}
		rsaKey, ok := any.(*rsa.PrivateKey)
		if !ok {
			return nil, errors.New("private key is not RSA")
		}
		return rsaKey, nil
	}
	return priv, nil
}

func decodePublic(pemStr string) (*rsa.PublicKey, error) {
	block, _ := pem.Decode([]byte(pemStr))
	if block == nil {
		return nil, errors.New("decode public PEM: no block found")
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		// Fall back to PKCS1.
		rsaPub, err2 := x509.ParsePKCS1PublicKey(block.Bytes)
		if err2 != nil {
			return nil, fmt.Errorf("parse public key: pkix=%v pkcs1=%v", err, err2)
		}
		return rsaPub, nil
	}
	rsaPub, ok := pub.(*rsa.PublicKey)
	if !ok {
		return nil, errors.New("public key is not RSA")
	}
	return rsaPub, nil
}
